/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : bigint,
  'pinterestPinId' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface ProductInput {
  'pinterestPinId' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductCount' : ActorMethod<[], bigint>,
  'getProductCountByCategory' : ActorMethod<[string], bigint>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByName' : ActorMethod<[string], Array<Product>>,
  'getProductsByPriceRange' : ActorMethod<[number, number], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];